console.log(`This is "script.js" file`);
let js = "JS is amazing!";
console.log(40 + 48 - 11 * 8);
console.log('Ivan');
let firtstName = 'Ivan';
let age = 34;
console.log(firtstName);
console.log(age);
firtstName = 'Vano';
console.log(firtstName);
let _name = "Sergey";
let $name = 'ivan';
console.log(_name, $name);